/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import ConexionSQL.Java_SQL;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Chefu
 */
public class pDispositivos extends javax.swing.JPanel {

    /**
     * Creates new form pDispositivos
     */
    public pDispositivos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bReporte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jIPDispositivo = new javax.swing.JTextField();
        jtIDDispositivo = new javax.swing.JTextField();
        jtNombreD = new javax.swing.JTextField();
        jtUbicacionD = new javax.swing.JTextField();
        jtEstadoD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtUsuarioD = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 36)); // NOI18N
        jLabel1.setText("Dispositivos");

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bReporte.setText("Reporte");
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        jLabel2.setText("IP del Dispositivo");

        jLabel3.setText("ID del Dispositivo");

        jLabel4.setText("Nombre del Disp");

        jLabel5.setText("Ubicación del Disp");

        jLabel6.setText("Estado:");

        jLabel7.setText("Usuario Master:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(bAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar)
                        .addGap(72, 72, 72)
                        .addComponent(bBuscar)
                        .addGap(64, 64, 64)
                        .addComponent(bModificar)
                        .addGap(18, 18, 18)
                        .addComponent(bReporte))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtIDDispositivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jIPDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtNombreD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtUbicacionD)
                                    .addComponent(jtEstadoD)
                                    .addComponent(jtUsuarioD)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminar)
                    .addComponent(bBuscar)
                    .addComponent(bModificar)
                    .addComponent(bAgregar)
                    .addComponent(bReporte))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jIPDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtIDDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtUbicacionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtEstadoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtUsuarioD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        // TODO add your handling code here:
        String Insertar = "insert into Dispositivos (IP_de_Dispositivo,ID_de_Dispositivo,Nombre_de_Dispositivo,Ubicacion_de_Dispositivo,Estado_de_Dispositivo) values (" + Integer.parseInt(jIPDispositivo.getText()) + "," + Integer.parseInt(jtIDDispositivo.getText()) + ",'" + jtNombreD.getText() + "','" + jtUbicacionD.getText() + "','" + jtEstadoD.getText() + "')";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();

        int result = insert(Insertar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Dispositivo insertado correctamente!", "Agregar Dispositivo", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Dispositivo ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        String Borrar = "DELETE FROM Dispositivos WHERE IP_de_Dispositivo = " + Integer.parseInt(jIPDispositivo.getText()) + "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();

        int result = insert(Borrar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Dispositivo borrado correctamente!", "Borrar Dispositivo", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Dispositivo ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        String Modificar = "UPDATE Dispositivos SET IP_de_Dispositivo = " + Integer.parseInt(jIPDispositivo.getText()) + " , Nombre_de_Dispositivo = '" + jtNombreD.getText() + "', Ubicacion_de_Dispositivo = '" + jtUbicacionD.getText() + "', Estado_de_Dispositivo =  '" + jtEstadoD.getText() + "' WHERE ID_de_Dispositivo = " + Integer.parseInt(jtIDDispositivo.getText()) + "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        int result = insert(Modificar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Dispositivo Modificado correctamente!", "Modificar Dispositivo", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Dispositivo ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_bModificarActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        ArrayList<String[]> filaSel = getDispositivos(con);
        for (String[] arreglohijo : filaSel) {
            jIPDispositivo.setText(arreglohijo[0].toString());
            jtIDDispositivo.setText(arreglohijo[1].toString());
            jtNombreD.setText(arreglohijo[2]);
            jtUbicacionD.setText(arreglohijo[3]);
            jtEstadoD.setText(arreglohijo[4]);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
        // TODO add your handling code here:
        html();
    }//GEN-LAST:event_bReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bReporte;
    private javax.swing.JTextField jIPDispositivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtEstadoD;
    private javax.swing.JTextField jtIDDispositivo;
    private javax.swing.JTextField jtNombreD;
    private javax.swing.JTextField jtUbicacionD;
    private javax.swing.JTextField jtUsuarioD;
    // End of variables declaration//GEN-END:variables
    public Integer insert(String query, Connection con) {
        try {
            Statement st = con.createStatement();
            st.executeUpdate(query);
            return 1;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR INSERT METHOD " + e.getErrorCode());
            return e.getErrorCode();
        }
    }

    public ArrayList<String[]> getDispositivos(Connection con) {
        ArrayList<String[]> queryResult = new ArrayList<>();
        ResultSet result = null;
        try ( Statement statement = con.createStatement();) {
            result = statement.executeQuery("SELECT * FROM Dispositivos WHERE IP_de_Dispositivo = " + Integer.parseInt(jIPDispositivo.getText()) + "");
            while (result.next()) {
                String[] obj = {result.getString(1), result.getString(2), result.getString(3), result.getString(4), result.getString(5)};
                queryResult.add(obj);
                System.out.println(result.getString(1) + result.getString(2) + result.getString(3) + result.getString(4) + result.getString(5));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR SELECT METHOD " + e.getErrorCode());
        }
        return queryResult;
    }

    private void html() {
        String rows = "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        BufferedWriter ficheroSalida;
        try {

            ficheroSalida = new BufferedWriter(new FileWriter(new File("ReporteD.html")));
            try ( Statement statement = con.createStatement();) {
                ResultSet result = statement.executeQuery("SELECT * FROM Dispositivos");
                while (result.next()) {
                    rows = rows + "            <tr>\n"
                            + "                <td>" + result.getObject("IP_de_Dispositivo") + "</td>\n"
                            + "                <td>" + result.getObject("ID_de_Dispositivo") + "</td>\n"
                            + "                <td>" + result.getObject("Nombre_de_Dispositivo") + "</td>\n"
                            + "                <td>" + result.getObject("Ubicacion_de_Dispositivo") + "</td>\n"
                            + "                <td>" + result.getObject("Estado_de_Dispositivo") + "</td>\n"
                            + "            </tr>";
                }
            } catch (SQLException e) {
            }
            ficheroSalida.write("<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "\n"
                    + "<head>\n"
                    + "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n"
                    + "        integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    + "    <title>Reportes</title>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body class=\"p-4\">\n"
                    + "    <table class=\"w-100 table table-dark table-hover\">\n"
                    + "        <thead>\n"
                    + "            <tr>\n"
                    + "                <th>IP</th>\n"
                    + "                <th>ID</th>\n"
                    + "                <th>Nombre</th>\n"
                    + "                <th>Ubicacion</th>\n"
                    + "                <th>Estado</th>\n"
                    + "            </tr>\n"
                    + "        </thead>\n"
                    + "        <tbody>\n"
                    + rows
                    + "        </tbody>\n"
                    + "    </table>\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>");
            ficheroSalida.close();
        } catch (IOException error) {
            System.out.println("El Error fue:" + error.getMessage());
        }
    }

    private void limpiarcampos() {
        jIPDispositivo.setText("");
        jtIDDispositivo.setText("");
        jtNombreD.setText("");
        jtUbicacionD.setText("");
        jtEstadoD.setText("");
        jIPDispositivo.requestFocus();
    }

}
