/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import ConexionSQL.Java_SQL;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Chefu
 */
public class pUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form pUsuarios
     */
    public pUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jIdUsuario = new javax.swing.JTextField();
        jNombreU = new javax.swing.JTextField();
        jDepUsuario = new javax.swing.JTextField();
        jNivelUsuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bReporte = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 36)); // NOI18N
        jLabel2.setText("Usuarios");

        jLabel1.setText("ID de Usuario:");

        jLabel3.setText("Nombre de Usuario:");

        jLabel4.setText("Departamento:");

        jLabel5.setText("Nivel de Acceso:");

        jLabel6.setText("Clientes:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bReporte.setText("Reporte");
        bReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 309, Short.MAX_VALUE)
                            .addComponent(jIdUsuario)
                            .addComponent(jNombreU)
                            .addComponent(jDepUsuario)
                            .addComponent(jNivelUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel2)
                        .addGap(0, 142, Short.MAX_VALUE)))
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(111, 111, 111)
                .addComponent(bBuscar)
                .addGap(68, 68, 68)
                .addComponent(bReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bEliminar)
                .addGap(131, 131, 131)
                .addComponent(bModificar)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDepUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jNivelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bBuscar)
                    .addComponent(bEliminar)
                    .addComponent(bModificar)
                    .addComponent(bReporte))
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Insertar = "insert into Usuarios (ID_de_Usuario,Nombre_de_Usuario,Departamento,Nivel_de_Acceso) values (" + Integer.parseInt(jIdUsuario.getText()) + ",'" + jNombreU.getText() + "','" + jDepUsuario.getText() + "','" + jNivelUsuario.getText() + "')";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();

        int result = insertC(Insertar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Usuario insertado correctamente!", "Agregar Cliente", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Usuario ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        ArrayList<String[]> filaSel = getUsuarios(con);
        for (String[] arreglohijo : filaSel) {
            jIdUsuario.setText(arreglohijo[0].toString());
            jNombreU.setText(arreglohijo[1].toString());
            jDepUsuario.setText(arreglohijo[2]);
            jNivelUsuario.setText(arreglohijo[3]);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReporteActionPerformed
        // TODO add your handling code here:
        html();
    }//GEN-LAST:event_bReporteActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        String Borrar = "DELETE FROM Usuarios WHERE ID_de_Usuario = " + Integer.parseInt(jIdUsuario.getText()) + "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();

        int result = insertC(Borrar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Cliente borrado correctamente!", "Borrar Dispositivo", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Cliente ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
        String Modificar = "UPDATE Usuarios SET Nombre_de_Usuario = '" + jNombreU.getText() + "', Departamento = '" + jDepUsuario.getText() + "', Nivel_de_Acceso =  '" + jNivelUsuario.getText() + "' WHERE ID_de_Usuario = " + Integer.parseInt(jIdUsuario.getText()) + "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        int result = insertC(Modificar, con);
        switch (result) {
            case 1 ->
                JOptionPane.showMessageDialog(null, "Usuario Modificado correctamente!", "Modificar Dispositivo", JOptionPane.INFORMATION_MESSAGE);
            case 2627 ->
                JOptionPane.showMessageDialog(null, "Usuario ya existente", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            case 547 ->
                JOptionPane.showMessageDialog(null, "Asegurese de que el proveedor exista", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
            default ->
                JOptionPane.showMessageDialog(null, "Error desconocido", "Error (" + result + ")", JOptionPane.ERROR_MESSAGE);
        }
        limpiarcampos();
    }//GEN-LAST:event_bModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jDepUsuario;
    private javax.swing.JTextField jIdUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNivelUsuario;
    private javax.swing.JTextField jNombreU;
    // End of variables declaration//GEN-END:variables

    public Integer insertC(String query, Connection con) {
        try {
            Statement st = con.createStatement();
            st.executeUpdate(query);
            return 1;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR INSERT METHOD " + e.getErrorCode());
            return e.getErrorCode();
        }
    }

    public ArrayList<String[]> getUsuarios(Connection con) {
        ArrayList<String[]> queryResult = new ArrayList<>();
        ResultSet result = null;
        try ( Statement statement = con.createStatement();) {
            result = statement.executeQuery("SELECT * FROM Usuarios WHERE ID_de_Usuario = " + Integer.parseInt(jIdUsuario.getText()) + "");
            while (result.next()) {
                String[] obj = {result.getString(1), result.getString(2), result.getString(3), result.getString(4)};
                queryResult.add(obj);
                System.out.println(result.getString(1) + result.getString(2) + result.getString(3) + result.getString(4));
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("ERROR SELECT METHOD " + e.getErrorCode());
        }
        return queryResult;
    }

    private void html() {
        String rows = "";
        Java_SQL cc = new Java_SQL();
        Connection con = cc.Conexion();
        BufferedWriter ficheroSalida;
        try {

            ficheroSalida = new BufferedWriter(new FileWriter(new File("ReporteU.html")));
            try ( Statement statement = con.createStatement();) {
                ResultSet result = statement.executeQuery("SELECT * FROM Usuarios");
                while (result.next()) {
                    rows = rows + "            <tr>\n"
                            + "                <td>" + result.getObject("ID_de_Usuario") + "</td>\n"
                            + "                <td>" + result.getObject("Nombre_de_Usuario") + "</td>\n"
                            + "                <td>" + result.getObject("Departamento") + "</td>\n"
                            + "                <td>" + result.getObject("Nivel_de_Acceso") + "</td>\n"
                            + "            </tr>";
                }
            } catch (SQLException e) {
            }
            ficheroSalida.write("<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "\n"
                    + "<head>\n"
                    + "    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n"
                    + "        integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                    + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                    + "    <title>Reportes</title>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body class=\"p-4\">\n"
                    + "    <table class=\"w-100 table table-dark table-hover\">\n"
                    + "        <thead>\n"
                    + "            <tr>\n"
                    + "                <th>ID</th>\n"
                    + "                <th>Nombre</th>\n"
                    + "                <th>Departamento</th>\n"
                    + "                <th>Nivel de Acceso</th>\n"
                    + "            </tr>\n"
                    + "        </thead>\n"
                    + "        <tbody>\n"
                    + rows
                    + "        </tbody>\n"
                    + "    </table>\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>");
            ficheroSalida.close();
        } catch (IOException error) {
            System.out.println("El Error fue:" + error.getMessage());
        }
    }

    private void limpiarcampos() {
        jIdUsuario.setText("");
        jNombreU.setText("");
        jDepUsuario.setText("");
        jNivelUsuario.setText("");
        jIdUsuario.requestFocus();
    }
}
